# Everything about cv2.imshow()

## Synatx:cv2.imshow(window name, ndarray)
***This function help to show image or numpy array in the  form of image***

In [1]:
import cv2
import numpy as np

In [2]:
matx = np.zeros((200,200)) # zeros matrix show black images
print(matx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
cv2.imshow("Zeros Image",matx)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [5]:
matx = np.ones((200,200)) # zeros matrix show black images
print(matx)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [6]:
cv2.imshow("Ones Image",matx)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [7]:
img_path=r"""E:\Videos\img_3.jpg"""
img = cv2.imread(img_path)

cv2.imshow("MASTI",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
img_path=r"""E:\Videos\img_3.jpg"""
img = cv2.imread(img_path)

cv2.imshow("Krishna_1",img) # show 1st windows

cv2.imshow("Krishn_2",img) # how 2nd windows

cv2.imshow("Krishna_3",img) # show 3rd widows

cv2.waitKey(0)
cv2.destroyAllWindows()